---
jenkins_port: 8085
jenkins_java_package: openjdk-21-jre
jenkins_package_state: present
jenkins_repository: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
jenkins_repository_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key"
jenkins_repository_file: /etc/apt/sources.list.d/jenkins.list
jenkins_keyring_file: /etc/apt/keyrings/jenkins-keyring.asc
